### ISSUE TITLE
[FR] 增加执行排序的命令

### ISSUE THREAD

**Issue by Moyf** [shu307/obsidian-nav-weight#1]
嗨！非常好用的插件！

不过现在只有 Ribbon 按钮一种执行的方式，我平时都是隐藏 Ribbon 的，想请问一下可以增加一个 Command 用来执行排序吗？

（以及，这个排序是每次启动 OB 之后，执行一次，就可以一直生效的吗？什么时候会需要刷新呢？）

**Comment by shu307** [comment]
现在是自动的了。
