### ISSUE TITLE
[BUG] 不含元数据的文件排序也会被影响

### ISSUE THREAD

**Issue by Moyf** [shu307/obsidian-nav-weight#2]
![image](https://github.com/user-attachments/assets/f553914d-3703-4cd1-9bf8-d1a50062eb5e)
如图，这些笔记都没有添加 `weight` 元数据，但是不论排序设置成什么，都无法生效。
（最下面的 2024-11-18 文件）

期望对于不带元数据的笔记，能保持原有的排序设置的顺序。

---

另外，可以添加一个“切换排序启用”的命令吗？能多一些操作上的自由度 👍🏻

**Comment by shu307** [comment]
应该修复了，命令也加了：[1.1.3](https://github.com/shu307/obsidian-nav-weight/releases/tag/1.1.3)

**Comment by Moyf** [comment]
> 应该修复了，命令也加了：[1.1.3](https://github.com/shu307/obsidian-nav-weight/releases/tag/1.1.3)

WOW 好快的修！感谢~~ ❤️️

**Comment by Moyf** [comment]
Nice，更新后已修复

**Comment by Moyf** [comment]
无伤大雅的小反馈：
![image](https://github.com/user-attachments/assets/588f411c-184d-402a-b255-b58eb3e45ef4)

命令面板默认会显示插件名，所以这个命令会变成重复的 `Nav Weight：Nav Weight：`
可以考虑改成 `Toggle Sorting by Nav Weight` 之类的  (￣▽￣)ノ
