### ISSUE TITLE
Enabling the plugin with no weights specified messes up sort order

### ISSUE THREAD

**Issue by mwhurley** [shu307/obsidian-nav-weight#3]
Imagine I have these folders in my vault (numbers in name):

- 1 First folder
- 2 Second folder
- 3 Third folder
- 4 Fourth folder

Right after I installed the plugin, but before I specified any weights, the sort order became 1, 3, 2, 4. In one of my folders I noticed the notes' sort order got messed up too.

I do not want to specify weights for all folders and notes. Any note where I don't specify a weight should be sorted within its default weight using the currently selected sort order selected in Obsidian.

**Comment by shu307** [comment]
Try [1.1.3](https://github.com/shu307/obsidian-nav-weight/releases/tag/1.1.3), should be fixed.
